---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: mongodb
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      hostname: mongodb
      restartPolicy: Always
      containers:
      - name: mongodb
        image: @@fawkes-discovery-db-image@@
        restartPolicy: Always
        volumeMounts:
        - mountPath: /data/configdb
          name: mongo-configdb
        - mountPath: /data/db
          name: mongo-datadb
        - mountPath: /docker-entrypoint-initdb.d/mongo-init.js:ro
          name: mongo-init
      volumes:
      - name: mongo-configdb
        persistentVolumeClaim:
          claimName: mongo-configdb
      - name: mongo-datadb
        persistentVolumeClaim:
          claimName: mongo-datadb
      - hostPath:
          path: /etc/fawkes-discovery/mongo-init.js
          type: File
        name: mongo-init