---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: @@fawkes-discovery-frontend-image@@
        hostname: frontend
        restartPolicy: Always
        env:
        - name: GIN_MODE
          value: "release"
        ports:
        - containerPort:
          hostPort:
        volumeMounts:
        - mountPath: /etc/fawkes-discovery
          readOnly: true
          name: fawkes-discovery-config-dir
      volumes:
      - hostPath:
          path: /etc/fawkes-discovery
          type: Directory
        name: fawkes-discovery-config-dir
