---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      hostname: frontend
      restartPolicy: Always
      containers:
      - name: frontend
        image: localhost/fawkes-discovery
        ports:
        - containerPort: 2020
          hostPort: 2020
        volumeMounts:
        - mountPath: /app/fawkes-discovery.yml
          name: fawkes-discovery-config
      volumes:
      - hostPath:
          path: /etc/fawkes-discovery/fawkes-discovery.yml
          type: File
        name: fawkes-discovery-config