apiVersion: v1
kind: Pod
metadata:
  labels:
    app: fawkes-discovery
  name: fawkes-discovery
spec:
  containers:
  - name: mongo
    image: docker.io/library/mongo
    restartPolicy: Always
    ports:
    - containerPort: 2020
      hostPort: 2020
    volumeMounts:
    - mountPath: /data/configdb
      name: mongo-configdb
    - mountPath: /data/db
      name: mongo-datadb
  - name: http-endpoint
    args:
    - --bind
    - :2020
    image: artifactory.algol60.net/fawkes-docker/stable/fawkes-discovery
    restartPolicy: Always
    volumeMounts:
    - mountPath: /app/fawkes-discovery.yml
      name: fawkes-discovery-config
  hostname: fawkes-discovery
  restartPolicy: Always
  volumes:
  - name: mongo-configdb
    persistentVolumeClaim:
      claimName: mongo-configdb
  - name: mongo-datadb
    persistentVolumeClaim:
      claimName: mongo-datadb
  - hostPath:
      path: /etc/fawkes-discovery/fawkes-discovery.yml
      type: File
    name: fawkes-discovery-config