---
######################
# Discovery Server api
######################
bind: ":8080"

######################
# MongoDB
######################
mongoserver: "mongodb-pod:27017"

database: "discovery"
collection: "discovery"

######################
# Mongo classifiers
######################
class: "/etc/fawkes-discovery/fawkes-discovery-classes.json"

